# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1038, 595)
        MainWindow.setStyleSheet("background-color: rgb(250, 250, 255);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.slider = QtWidgets.QScrollBar(self.centralwidget)
        self.slider.setGeometry(QtCore.QRect(750, 450, 160, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.slider.setFont(font)
        self.slider.setOrientation(QtCore.Qt.Horizontal)
        self.slider.setObjectName("slider")
        self.label_question = QtWidgets.QLabel(self.centralwidget)
        self.label_question.setGeometry(QtCore.QRect(200, 110, 750, 70))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label_question.setFont(font)
        self.label_question.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_question.setObjectName("label_question")
        self.label_answer1 = QtWidgets.QLabel(self.centralwidget)
        self.label_answer1.setGeometry(QtCore.QRect(200, 190, 750, 50))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label_answer1.setFont(font)
        self.label_answer1.setObjectName("label_answer1")
        self.label_answer2 = QtWidgets.QLabel(self.centralwidget)
        self.label_answer2.setGeometry(QtCore.QRect(200, 250, 750, 50))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label_answer2.setFont(font)
        self.label_answer2.setStyleSheet("")
        self.label_answer2.setObjectName("label_answer2")
        self.label_answer3 = QtWidgets.QLabel(self.centralwidget)
        self.label_answer3.setGeometry(QtCore.QRect(200, 310, 750, 50))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label_answer3.setFont(font)
        self.label_answer3.setObjectName("label_answer3")
        self.label_answer4 = QtWidgets.QLabel(self.centralwidget)
        self.label_answer4.setGeometry(QtCore.QRect(200, 370, 750, 50))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label_answer4.setFont(font)
        self.label_answer4.setObjectName("label_answer4")
        self.button_answer = QtWidgets.QPushButton(self.centralwidget)
        self.button_answer.setGeometry(QtCore.QRect(500, 440, 100, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.button_answer.setFont(font)
        self.button_answer.setObjectName("button_answer")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(160, 445, 180, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.checkBox_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_1.setGeometry(QtCore.QRect(140, 190, 51, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_1.sizePolicy().hasHeightForWidth())
        self.checkBox_1.setSizePolicy(sizePolicy)
        self.checkBox_1.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.checkBox_1.setFont(font)
        self.checkBox_1.setAutoFillBackground(False)
        self.checkBox_1.setStyleSheet("QCheckBox::indicator { width: 50px; height: 50px;};")
        self.checkBox_1.setText("")
        self.checkBox_1.setIconSize(QtCore.QSize(30, 30))
        self.checkBox_1.setTristate(False)
        self.checkBox_1.setObjectName("checkBox_1")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 0, 181, 111))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("../../../pictures/koziy.PNG"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(329, 19, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label_title.setFont(font)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(140, 250, 50, 50))
        self.checkBox_2.setStyleSheet("QCheckBox::indicator { width: 50px; height: 50px;};")
        self.checkBox_2.setText("")
        self.checkBox_2.setIconSize(QtCore.QSize(30, 30))
        self.checkBox_2.setTristate(False)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(140, 310, 50, 50))
        self.checkBox_3.setStyleSheet("QCheckBox::indicator { width: 50px; height: 50px;};")
        self.checkBox_3.setText("")
        self.checkBox_3.setIconSize(QtCore.QSize(30, 30))
        self.checkBox_3.setTristate(False)
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_4.setGeometry(QtCore.QRect(140, 370, 50, 50))
        self.checkBox_4.setStyleSheet("QCheckBox::indicator { width: 50px; height: 50px;};")
        self.checkBox_4.setText("")
        self.checkBox_4.setIconSize(QtCore.QSize(30, 30))
        self.checkBox_4.setTristate(False)
        self.checkBox_4.setObjectName("checkBox_4")
        self.label_progress = QtWidgets.QLabel(self.centralwidget)
        self.label_progress.setGeometry(QtCore.QRect(720, 19, 221, 81))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label_progress.setFont(font)
        self.label_progress.setObjectName("label_progress")
        self.button_finish = QtWidgets.QPushButton(self.centralwidget)
        self.button_finish.setGeometry(QtCore.QRect(50, 130, 100, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.button_finish.setFont(font)
        self.button_finish.setObjectName("button_finish")
        self.comboBox_task = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_task.setGeometry(QtCore.QRect(320, 60, 340, 30))
        self.comboBox_task.setObjectName("comboBox_task")
        self.checkBox_1.raise_()
        self.slider.raise_()
        self.label_question.raise_()
        self.label_answer1.raise_()
        self.label_answer2.raise_()
        self.label_answer3.raise_()
        self.label_answer4.raise_()
        self.button_answer.raise_()
        self.comboBox.raise_()
        self.label_6.raise_()
        self.label_title.raise_()
        self.checkBox_2.raise_()
        self.checkBox_3.raise_()
        self.checkBox_4.raise_()
        self.label_progress.raise_()
        self.button_finish.raise_()
        self.comboBox_task.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1038, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_question.setText(_translate("MainWindow", "You should write question here"))
        self.label_answer1.setText(_translate("MainWindow", "Answer 1"))
        self.label_answer2.setText(_translate("MainWindow", "Answer 2"))
        self.label_answer3.setText(_translate("MainWindow", "Answer 3"))
        self.label_answer4.setText(_translate("MainWindow", "Answer 4"))
        self.button_answer.setText(_translate("MainWindow", "Answer"))
        self.label_title.setText(_translate("MainWindow", "Тестирующая система"))
        self.label_progress.setText(_translate("MainWindow", "Your progress:"))
        self.button_finish.setText(_translate("MainWindow", "Finish"))

